<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
    <Folder Include="Configuration\" />
    <Folder Include="Logging\" />
    <Folder Include="Persistence\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DevJourney.Application\DevJourney.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.22.0" />
    <PackageReference Include="Hangfire" Version="1.8.24" />
    <PackageReference Include="Hangfire.Core" Version="1.8.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="SixLabors.ImageSharp" Version="4.1.2" />
  </ItemGroup>

</Project>
